### ISSUE TITLE
ReadLine does not throw a FormatException

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/guess_game#7]
https://github.com/nsofiia/guess_game/blob/671057a596dbab0b52bc10840a00d40d6945a125/guessGame/Program.cs#L67-L78

Do you really need this whole loop and exception handling?
You dont try to convert text to a number here, so there should no exception be thrown and you could remove all the unused code

**Comment by incredibleLeitman** [comment]
But you still have the while loop around the reading of answer... in fact, if the user puts in a "0" you would ask him again ☝️ 


```
System.Environment.Exit(1);
```
Takes a parameter and usually this is the error Code if something happend... in case, the program was just closed without any error you would use 0

**Comment by nsofiia** [comment]
this is fixed @incredibleLeitman

**Comment by incredibleLeitman** [comment]
Did you miss something to commit? 🤔 
Because I still see "Exit(1)" in there
